<?php
// kernel-load.php

$kernel_logs = [
"[  OK  ] Started plymouth-start.service - Show Plymouth Boot Screen.",
"[  OK  ] Started systemd-ask-password-plymo…quests to Plymouth Directory Watch.",
"[  OK  ] Reached target cryptsetup.target - Local Encrypted Volumes.",
"[  OK  ] Reached target paths.target - Path Units.",
         "Starting systemd-battery-check.ser… battery level during early boot...",
"[  OK  ] Stopped systemd-vconsole-setup.service - Virtual Console Setup.",
         "Stopping systemd-vconsole-setup.service - Virtual Console Setup...",
         "Starting systemd-vconsole-setup.service - Virtual Console Setup...",
"[  OK  ] Finished systemd-battery-check.ser…ck battery level during early boot.",
"[  OK  ] Finished systemd-vconsole-setup.service - Virtual Console Setup.",
         "Mounting sys-kernel-config.mount - Kernel Configuration File System...",
"[  OK  ] Mounted sys-kernel-config.mount - Kernel Configuration File System.",
"[  OK  ] Reached target sysinit.target - System Initialization.",
"[  OK  ] Reached target basic.target - Basic System.",
"[  OK  ] Found device dev-disk-by\x2duuid-4…40ZNS256G NVMe KIOXIA 256GB fedora.",
"[  OK  ] Reached target initrd-root-device.target - Initrd Root Device.",
"[  OK  ] Finished dracut-initqueue.service - dracut initqueue hook.",
"[  OK  ] Reached target remote-fs-pre.targe…reparation for Remote File Systems.",
"[  OK  ] Reached target remote-cryptsetup.target - Remote Encrypted Volumes.",
"[  OK  ] Reached target remote-fs.target - Remote File Systems.",
         "Starting dracut-pre-mount.service - dracut pre-mount hook...",
"[  OK  ] Finished dracut-pre-mount.service - dracut pre-mount hook.",
         "Starting systemd-fsck-root.service…7e8e-8eaf-4701-8a88-ec9e956926be...",
"[  OK  ] Finished systemd-fsck-root.service…567e8e-8eaf-4701-8a88-ec9e956926be.",
         "Mounting sysroot.mount - /sysroot...",
"[  OK  ] Mounted sysroot.mount - /sysroot.",
"[  OK  ] Reached target initrd-root-fs.target - Initrd Root File System.",
         "Starting initrd-parse-etc.service …ints Configured in the Real Root...",
"[  OK  ] Finished initrd-parse-etc.service …points Configured in the Real Root.",
"[  OK  ] Reached target initrd-fs.target - Initrd File Systems.",
"[  OK  ] Reached target initrd.target - Initrd Default Target.",
         "Starting dracut-pre-pivot.service …racut pre-pivot and cleanup hook...",
"[  OK  ] Finished dracut-pre-pivot.service - dracut pre-pivot and cleanup hook.",
         "Starting initrd-cleanup.service - …ing Up and Shutting Down Daemons...",
"[  OK  ] Stopped target network.target - Network.",
"[  OK  ] Stopped target remote-cryptsetup.target - Remote Encrypted Volumes.",
"[  OK  ] Stopped target timers.target - Timer Units.",
"[  OK  ] Stopped target tpm2.target - Trusted Platform Module.",
"[  OK  ] Closed dbus.socket - D-Bus System Message Bus Socket.",
"[  OK  ] Stopped dracut-pre-pivot.service - dracut pre-pivot and cleanup hook.",
"[  OK  ] Stopped target initrd.target - Initrd Default Target.",
"[  OK  ] Stopped target basic.target - Basic System.",
"[  OK  ] Stopped target initrd-root-device.target - Initrd Root Device.",
"[  OK  ] Stopped target initrd-usr-fs.target - Initrd /usr File System.",
"[  OK  ] Stopped target paths.target - Path Units.",
"[  OK  ] Stopped target remote-fs.target - Remote File Systems.",
"[  OK  ] Stopped target remote-fs-pre.targe…reparation for Remote File Systems.",
"[  OK  ] Stopped target slices.target - Slice Units.",
"[  OK  ] Stopped target sockets.target - Socket Units.",
"[  OK  ] Stopped target sysinit.target - System Initialization.",
"[  OK  ] Stopped target local-fs.target - Local File Systems.",
"[  OK  ] Stopped target local-fs-pre.target…Preparation for Local File Systems.",
"[  OK  ] Stopped target swap.target - Swaps.",
"[  OK  ] Closed iscsid.socket - Open-iSCSI iscsid Socket.",
"[  OK  ] Closed iscsiuio.socket - Open-iSCSI iscsiuio Socket.",
"[  OK  ] Stopped dracut-pre-mount.service - dracut pre-mount hook.",
"[  OK  ] Stopped target cryptsetup.target - Local Encrypted Volumes.",
"[  OK  ] Stopped dracut-initqueue.service - dracut initqueue hook.",
         "Starting plymouth-switch-root.serv…e - Plymouth switch root service...",
"[  OK  ] Stopped systemd-battery-check.serv…ck battery level during early boot.",
"[  OK  ] Stopped systemd-sysctl.service - Apply Kernel Variables.",
"[  OK  ] Stopped systemd-modules-load.service - Load Kernel Modules.",
"[  OK  ] Stopped systemd-tmpfiles-setup.ser…reate System Files and Directories.",
"[  OK  ] Stopped systemd-udev-trigger.service - Coldplug All udev Devices.",
"[  OK  ] Stopped dracut-pre-trigger.service - dracut pre-trigger hook.",
         "Stopping systemd-udevd.service - R…ager for Device Events and Files...",
"[  OK  ] Finished initrd-cleanup.service - …aning Up and Shutting Down Daemons.",
"[  OK  ] Stopped systemd-udevd.service - Ru…anager for Device Events and Files.",
"[  OK  ] Closed systemd-udevd-control.socket - udev Control Socket.",
"[  OK  ] Closed systemd-udevd-kernel.socket - udev Kernel Socket.",
"[  OK  ] Stopped dracut-pre-udev.service - dracut pre-udev hook.",
"[  OK  ] Stopped dracut-cmdline.service - dracut cmdline hook.",
"[  OK  ] Stopped dracut-cmdline-ask.service… for additional cmdline parameters.",
         "Starting initrd-udevadm-cleanup-db.service - Cleanup udev Database...",
"[  OK  ] Stopped systemd-tmpfiles-setup-dev…Create Static Device Nodes in /dev.",
"[  OK  ] Stopped systemd-sysusers.service - Create System Users.",
"[  OK  ] Stopped systemd-tmpfiles-setup-dev…ic Device Nodes in /dev gracefully.",
"[  OK  ] Stopped kmod-static-nodes.service …Create List of Static Device Nodes.",
"[  OK  ] Finished initrd-udevadm-cleanup-db.service - Cleanup udev Database.",
"[  OK  ] Reached target initrd-switch-root.target - Switch Root.",
"[  OK  ] Finished plymouth-switch-root.service - Plymouth switch root service.",
         "Starting initrd-switch-root.service - Switch Root...",
"[  OK  ] Stopped initrd-switch-root.service - Switch Root.",
"[  OK  ] Created slice system-getty.slice - Slice /system/getty.",
"[  OK  ] Created slice system-systemd\x2dfs…slice - Slice /system/systemd-fsck.",
"[  OK  ] Created slice system-systemd\x2dzr…- Slice /system/systemd-zram-setup.",
"[  OK  ] Created slice user.slice - User and Session Slice.",
"[  OK  ] Started systemd-ask-password-wall.…d Requests to Wall Directory Watch.",
"[  OK  ] Set up automount proc-sys-fs-binfm…ormats File System Automount Point.",
         "Expecting device dev-disk-by\x2duu…7e8e-8eaf-4701-8a88-ec9e956926be...",
         "Expecting device dev-disk-by\x2duu…ce - /dev/disk/by-uuid/A6E7-ECA0...",
         "Expecting device dev-disk-by\x2duu…3917-a202-469c-a6cf-b81394313237...",
         "Expecting device dev-zram0.device - /dev/zram0...",
"[  OK  ] Reached target cryptsetup.target - Local Encrypted Volumes.",
"[  OK  ] Reached target getty.target - Login Prompts.",
"[  OK  ] Stopped target initrd-switch-root.target - Switch Root.",
"[  OK  ] Stopped target initrd-fs.target - Initrd File Systems.",
"[  OK  ] Stopped target initrd-root-fs.target - Initrd Root File System.",
"[  OK  ] Reached target integritysetup.targ… Local Integrity Protected Volumes.",
"[  OK  ] Reached target rpc_pipefs.target.",
"[  OK  ] Reached target slices.target - Slice Units.",
"[  OK  ] Reached target veritysetup.target - Local Verity Protected Volumes.",
"[  OK  ] Listening on dm-event.socket - Device-mapper event daemon FIFOs.",
"[  OK  ] Listening on lvm2-lvmpolld.socket - LVM2 poll daemon socket.",
"[  OK  ] Listening on systemd-coredump.socket - Process Core Dump Socket.",
"[  OK  ] Listening on systemd-creds.socket - Credential Encryption/Decryption.",
"[  OK  ] Listening on systemd-initctl.socke…- initctl Compatibility Named Pipe.",
"[  OK  ] Listening on systemd-journald-audit.socket - Journal Audit Socket.",
"[  OK  ] Listening on systemd-oomd.socket -… Out-Of-Memory (OOM) Killer Socket.",
"[  OK  ] Listening on systemd-udevd-control.socket - udev Control Socket.",
"[  OK  ] Listening on systemd-udevd-kernel.socket - udev Kernel Socket.",
"[  OK  ] Listening on systemd-userdbd.socket - User Database Manager Socket.",
         "Mounting dev-hugepages.mount - Huge Pages File System...",
         "Mounting dev-mqueue.mount - POSIX Message Queue File System...",
         "Mounting sys-kernel-debug.mount - Kernel Debug File System...",
         "Mounting sys-kernel-tracing.mount - Kernel Trace File System...",
         "Starting kmod-static-nodes.service…eate List of Static Device Nodes...",
         "Starting lvm2-monitor.service - Mo…ing dmeventd or progress polling...",
         "Starting modprobe@configfs.service - Load Kernel Module configfs...",
         "Starting modprobe@dm_mod.service - Load Kernel Module dm_mod...",
         "Starting modprobe@drm.service - Load Kernel Module drm...",
         "Starting modprobe@efi_pstore.servi… - Load Kernel Module efi_pstore...",
         "Starting modprobe@fuse.service - Load Kernel Module fuse...",
         "Starting modprobe@loop.service - Load Kernel Module loop...",
"[  OK  ] Stopped plymouth-switch-root.service - Plymouth switch root service.",
"[  OK  ] Stopped systemd-fsck-root.service - File System Check on Root Device.",
         "Starting systemd-hibernate-clear.s…ear Stale Hibernate Storage Info...",
         "Starting systemd-journald.service - Journal Service...",
         "Starting systemd-modules-load.service - Load Kernel Modules...",
         "Starting systemd-remount-fs.servic…unt Root and Kernel File Systems...",
         "Starting systemd-udev-load-credent…Load udev Rules from Credentials...",
         "Starting systemd-udev-trigger.service - Coldplug All udev Devices...",
"[  OK  ] Mounted dev-hugepages.mount - Huge Pages File System.",
"[  OK  ] Mounted dev-mqueue.mount - POSIX Message Queue File System.",
"[  OK  ] Mounted sys-kernel-debug.mount - Kernel Debug File System.",
"[  OK  ] Mounted sys-kernel-tracing.mount - Kernel Trace File System.",
"[  OK  ] Finished kmod-static-nodes.service…Create List of Static Device Nodes.",
"[  OK  ] Finished modprobe@configfs.service - Load Kernel Module configfs.",
"[  OK  ] Finished modprobe@dm_mod.service - Load Kernel Module dm_mod.",
"[  OK  ] Finished modprobe@drm.service - Load Kernel Module drm.",
"[  OK  ] Finished modprobe@efi_pstore.service - Load Kernel Module efi_pstore.",
"[  OK  ] Finished modprobe@fuse.service - Load Kernel Module fuse.",
"[  OK  ] Finished modprobe@loop.service - Load Kernel Module loop.",
"[  OK  ] Finished systemd-hibernate-clear.s…Clear Stale Hibernate Storage Info.",
"[  OK  ] Finished systemd-modules-load.service - Load Kernel Modules.",
"[  OK  ] Finished systemd-remount-fs.servic…mount Root and Kernel File Systems.",
         "Mounting sys-fs-fuse-connections.mount - FUSE Control File System...",
         "Starting systemd-random-seed.service - Load/Save OS Random Seed...",
         "Starting systemd-sysctl.service - Apply Kernel Variables...",
         "Starting systemd-tmpfiles-setup-de… Device Nodes in /dev gracefully...",
"[  OK  ] Mounted sys-fs-fuse-connections.mount - FUSE Control File System.",
"[  OK  ] Finished systemd-udev-load-credent…- Load udev Rules from Credentials.",
"[  OK  ] Finished lvm2-monitor.service - Mo…using dmeventd or progress polling.",
"[  OK  ] Finished systemd-random-seed.service - Load/Save OS Random Seed.",
"[  OK  ] Finished systemd-sysctl.service - Apply Kernel Variables.",
"[  OK  ] Started systemd-journald.service - Journal Service.",
         "Starting systemd-journal-flush.ser…sh Journal to Persistent Storage...",
         "Starting systemd-userdbd.service - User Database Manager...",
"[  OK  ] Started systemd-userdbd.service - User Database Manager.",
"[  OK  ] Finished systemd-udev-trigger.service - Coldplug All udev Devices.",
"[  OK  ] Finished systemd-tmpfiles-setup-de…ic Device Nodes in /dev gracefully.",
         "Starting systemd-tmpfiles-setup-de…eate Static Device Nodes in /dev...",
"[  OK  ] Finished systemd-tmpfiles-setup-de…Create Static Device Nodes in /dev.",
"[  OK  ] Reached target local-fs-pre.target…Preparation for Local File Systems.",
         "Starting systemd-udevd.service - R…ager for Device Events and Files...",
"[  OK  ] Finished systemd-journal-flush.ser…lush Journal to Persistent Storage.",
"[  OK  ] Started systemd-udevd.service - Ru…anager for Device Events and Files.",
         "Starting modprobe@configfs.service - Load Kernel Module configfs...",
         "Starting modprobe@fuse.service - Load Kernel Module fuse...",
"[  OK  ] Found device dev-zram0.device - /dev/zram0.",
         "Starting systemd-zram-setup@zram0.…vice - Create swap on /dev/zram0...",
"[  OK  ] Finished modprobe@fuse.service - Load Kernel Module fuse.",
"[  OK  ] Finished modprobe@configfs.service - Load Kernel Module configfs.",
"[  OK  ] Reached target tpm2.target - Trusted Platform Module.",
"[  OK  ] Finished systemd-zram-setup@zram0.service - Create swap on /dev/zram0.",
         "Activating swap dev-zram0.swap - Compressed Swap on /dev/zram0...",
"[  OK  ] Found device dev-disk-by\x2duuid-4…40ZNS256G NVMe KIOXIA 256GB fedora.",
         "Starting systemd-fsck@dev-disk-by\…k on /dev/disk/by-uuid/A6E7-ECA0...",
         "Starting systemd-fsck@dev-disk-by\…3917-a202-469c-a6cf-b81394313237...",
"[  OK  ] Activated swap dev-zram0.swap - Compressed Swap on /dev/zram0.",
"[  OK  ] Reached target swap.target - Swaps.",
"[  OK  ] Created slice system-systemd\x2dba… - Slice /system/systemd-backlight.",
         "Starting systemd-backlight@backlig…ess of backlight:intel_backlight...",
"[  OK  ] Finished systemd-fsck@dev-disk-by\…193917-a202-469c-a6cf-b81394313237.",
"[  OK  ] Finished systemd-fsck@dev-disk-by\…eck on /dev/disk/by-uuid/A6E7-ECA0.",
"[  OK  ] Finished systemd-backlight@backlig…tness of backlight:intel_backlight.",
"[  OK  ] Stopped systemd-vconsole-setup.service - Virtual Console Setup.",
         "Stopping systemd-vconsole-setup.service - Virtual Console Setup...",
         "Starting systemd-vconsole-setup.service - Virtual Console Setup...",
"[  OK  ] Listening on systemd-rfkill.socket…ll Switch Status /dev/rfkill Watch.",
"[  OK  ] Finished systemd-vconsole-setup.service - Virtual Console Setup.",
         "Starting systemd-backlight@leds:de…ness of leds:dell::kbd_backlight...",
         "Starting systemd-rfkill.service - Load/Save RF Kill Switch Status...",
         "Starting modprobe@dm_mod.service - Load Kernel Module dm_mod...",
         "Starting modprobe@efi_pstore.servi… - Load Kernel Module efi_pstore...",
         "Starting modprobe@loop.service - Load Kernel Module loop...",
"[  OK  ] Started systemd-rfkill.service - Load/Save RF Kill Switch Status.",
"[  OK  ] Finished systemd-backlight@leds:de…htness of leds:dell::kbd_backlight.",
"[  OK  ] Finished modprobe@dm_mod.service - Load Kernel Module dm_mod.",
"[  OK  ] Finished modprobe@efi_pstore.service - Load Kernel Module efi_pstore.",
"[  OK  ] Finished modprobe@loop.service - Load Kernel Module loop.",
         "Mounting boot.mount - /boot...",
         "Mounting home.mount - /home...",
         "Mounting tmp.mount - Temporary Directory /tmp...",
"[  OK  ] Mounted home.mount - /home.",
"[  OK  ] Mounted tmp.mount - Temporary Directory /tmp.",
"[  OK  ] Mounted boot.mount - /boot.",
         "Mounting boot-efi.mount - /boot/efi...",
"[  OK  ] Mounted boot-efi.mount - /boot/efi.",
"[  OK  ] Reached target local-fs.target - Local File Systems.",
"[  OK  ] Listening on systemd-bootctl.socket - Boot Entries Service Socket.",
"[  OK  ] Listening on systemd-sysext.socket… System Extension Image Management.",
         "Starting plymouth-read-write.servi…ymouth To Write Out Runtime Data...",
         "Starting systemd-tmpfiles-setup.se…ate System Files and Directories...",
"[  OK  ] Finished plymouth-read-write.servi…Plymouth To Write Out Runtime Data.",
"[  OK  ] Finished systemd-tmpfiles-setup.se…reate System Files and Directories.",
         "Starting auditd.service - Security Audit Logging Service...",
         "Starting systemd-oomd.service - Us…space Out-Of-Memory (OOM) Killer...",
         "Starting systemd-resolved.service - Network Name Resolution...",
"[  OK  ] Started auditd.service - Security Audit Logging Service.",
         "Starting audit-rules.service - Load Audit Rules...",
         "Starting systemd-update-utmp.servi…ord System Boot/Shutdown in UTMP...",
"[  OK  ] Finished systemd-update-utmp.servi…ecord System Boot/Shutdown in UTMP.",
"[  OK  ] Finished audit-rules.service - Load Audit Rules.",
"[  OK  ] Started systemd-oomd.service - Userspace Out-Of-Memory (OOM) Killer.",
"[  OK  ] Started systemd-resolved.service - Network Name Resolution.",
"[  OK  ] Reached target nss-lookup.target - Host and Network Name Lookups.",
"[  OK  ] Reached target sysinit.target - System Initialization.",
"[  OK  ] Started cups.path - CUPS Scheduler.",
"[  OK  ] Created slice system-cups.slice - CUPS Slice.",
"[  OK  ] Started dnf-makecache.timer - dnf5 makecache.",
"[  OK  ] Started fstrim.timer - Discard unused filesystem blocks once a week.",
"[  OK  ] Started logrotate.timer - Daily rotation of log files.",
"[  OK  ] Started plocate-updatedb.timer - Update the plocate database daily.",
"[  OK  ] Started raid-check.timer - Weekly RAID setup health check.",
"[  OK  ] Started systemd-tmpfiles-clean.tim…y Cleanup of Temporary Directories.",
"[  OK  ] Started unbound-anchor.timer - dai…f the root trust anchor for DNSSEC.",
"[  OK  ] Reached target paths.target - Path Units.",
"[  OK  ] Reached target timers.target - Timer Units.",
"[  OK  ] Listening on avahi-daemon.socket -…DNS/DNS-SD Stack Activation Socket.",
"[  OK  ] Listening on cups.socket - CUPS Scheduler.",
"[  OK  ] Listening on dbus.socket - D-Bus System Message Bus Socket.",
"[  OK  ] Listening on iscsid.socket - Open-iSCSI iscsid Socket.",
"[  OK  ] Listening on iscsiuio.socket - Open-iSCSI iscsiuio Socket.",
"[  OK  ] Listening on pcscd.socket - PC/SC Smart Card Daemon Activation Socket.",
"[  OK  ] Listening on sshd-unix-local.socke…temd-ssh-generator, AF_UNIX Local).",
"[  OK  ] Listening on sssd-kcm.socket - SSS…ros Cache Manager responder socket.",
"[  OK  ] Listening on systemd-hostnamed.socket - Hostname Service Socket.",
"[  OK  ] Reached target sockets.target - Socket Units.",
         "Starting dbus-broker.service - D-Bus System Message Bus...",
"[  OK  ] Started dbus-broker.service - D-Bus System Message Bus.",
"[  OK  ] Reached target basic.target - Basic System.",
         "Starting abrtd.service - ABRT Daemon...",
         "Starting avahi-daemon.service - Avahi mDNS/DNS-SD Stack...",
         "Starting bluetooth.service - Bluetooth service...",
         "Starting dracut-shutdown.service -…store /run/initramfs on shutdown...",
"[  OK  ] Started irqbalance.service - irqbalance daemon.",
         "Starting chronyd.service - NTP client/server...",
"[  OK  ] Started mcelog.service - Machine Check Exception Logging Daemon.",
         "Starting polkit.service - Authorization Manager...",
         "Starting rtkit-daemon.service - Re…imeKit Scheduling Policy Service...",
         "Starting smartd.service - Self Mon…orting Technology (SMART) Daemon...",
"[  OK  ] Reached target nss-user-lookup.target - User and Group Name Lookups.",
         "Starting accounts-daemon.service - Accounts Service...",
         "Starting switcheroo-control.servic…Switcheroo Control Proxy service...",
         "Starting systemd-homed.service - Home Area Manager...",
         "Starting systemd-logind.service - User Login Management...",
         "Starting udisks2.service - Disk Manager...",
         "Starting upower.service - Daemon for power management...",
"[  OK  ] Finished dracut-shutdown.service - Restore /run/initramfs on shutdown.",
"[  OK  ] Started avahi-daemon.service - Avahi mDNS/DNS-SD Stack.",
"[  OK  ] Started smartd.service - Self Moni…eporting Technology (SMART) Daemon.",
"[  OK  ] Started systemd-homed.service - Home Area Manager.",
"[  OK  ] Finished systemd-homed-activate.service - Home Area Activation.",
"[  OK  ] Started rtkit-daemon.service - RealtimeKit Scheduling Policy Service.",
"[  OK  ] Started bluetooth.service - Bluetooth service.",
"[  OK  ] Reached target bluetooth.target - Bluetooth Support.",
"[  OK  ] Started switcheroo-control.service - Switcheroo Control Proxy service.",
"[  OK  ] Started chronyd.service - NTP client/server.",
         "Starting systemd-hostnamed.service - Hostname Service...",
"[  OK  ] Started systemd-logind.service - User Login Management.",
"[  OK  ] Started polkit.service - Authorization Manager.",
         "Starting ModemManager.service - Modem Manager...",
         "Starting firewalld.service - firewalld - dynamic firewall daemon...",
"[  OK  ] Started accounts-daemon.service - Accounts Service.",
"[  OK  ] Started systemd-hostnamed.service - Hostname Service.",
"[  OK  ] Started udisks2.service - Disk Manager.",
"[  OK  ] Started abrtd.service - ABRT Daemon.",
"[  OK  ] Started abrt-journal-core.service - ABRT coredumpctl message creator.",
"[  OK  ] Started abrt-oops.service - ABRT kernel log watcher.",
"[  OK  ] Started abrt-xorg.service - ABRT Xorg log watcher.",
"[  OK  ] Started upower.service - Daemon for power management.",
"[  OK  ] Started ModemManager.service - Modem Manager.",
"[  OK  ] Started alsa-state.service - Manag…und Card State (restore and store).",
"[  OK  ] Reached target sound.target - Sound Card.",
"[  OK  ] Started firewalld.service - firewalld - dynamic firewall daemon.",
"[  OK  ] Reached target network-pre.target - Preparation for Network.",
         "Starting NetworkManager.service - Network Manager...",
         "Starting NetworkManager-dispatcher…anager Script Dispatcher Service...",
"[  OK  ] Started NetworkManager-dispatcher.… Manager Script Dispatcher Service.",
"[  OK  ] Started NetworkManager.service - Network Manager.",
         "Starting NetworkManager-wait-onlin…ce - Network Manager Wait Online...",
         "Starting wpa_supplicant.service - WPA supplicant...",
"[  OK  ] Started wpa_supplicant.service - WPA supplicant.",
"[  OK  ] Reached target network.target - Network.",
         "Starting cups.service - CUPS Scheduler...",
         "Starting gssproxy.service - GSSAPI Proxy Daemon...",
         "Starting mariadb.service - MariaDB 10.11 database server...",
         "Starting php-fpm.service - The PHP FastCGI Process Manager...",
         "Starting tuned.service - Dynamic System Tuning Daemon...",
"[  OK  ] Started cups.service - CUPS Scheduler.",
"[  OK  ] Started gssproxy.service - GSSAPI Proxy Daemon.",
"[  OK  ] Reached target nfs-client.target - NFS client services.",
"[  OK  ] Reached target remote-fs-pre.targe…reparation for Remote File Systems.",
"[  OK  ] Reached target remote-cryptsetup.target - Remote Encrypted Volumes.",
"[  OK  ] Started php-fpm.service - The PHP FastCGI Process Manager.",
"[  OK  ] Started tuned.service - Dynamic System Tuning Daemon.",
         "Starting tuned-ppd.service - PPD-to-TuneD API Translation Daemon...",
"[  OK  ] Started mariadb.service - MariaDB 10.11 database server.",
"[  OK  ] Started tuned-ppd.service - PPD-to-TuneD API Translation Daemon.",
"[  OK  ] Finished NetworkManager-wait-onlin…vice - Network Manager Wait Online.",
"[  OK  ] Reached target network-online.target - Network is Online.",
"[  OK  ] Reached target remote-fs.target - Remote File Systems.",
         "Starting nginx.service - The nginx HTTP and reverse proxy server...",
         "Starting rpc-statd-notify.service - Notify NFS peers of a restart...",
         "Starting rsyslog.service - System Logging Service...",
         "Starting systemd-user-sessions.service - Permit User Sessions...",
"[  OK  ] Started rpc-statd-notify.service - Notify NFS peers of a restart.",
"[  OK  ] Finished systemd-user-sessions.service - Permit User Sessions.",
"[  OK  ] Started atd.service - Deferred execution scheduler.",
"[  OK  ] Started crond.service - Command Scheduler.",
         "Starting plymouth-quit-wait.servic…d until boot process finishes up...",
         "Starting plymouth-quit.service - Terminate Plymouth Boot Screen...",
"[  OK  ] Started rsyslog.service - System Logging Service."

];

return $kernel_logs;

